// Code generated by "esc -include=.json$ -o plugin/json/JSONPlugin.go -pkg jsonplugin plugin/json/"; DO NOT EDIT.

package jsonplugin

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/plugin/json/coremail_config_dump.json": {
		name:    "coremail_config_dump.json",
		local:   "plugin/json/coremail_config_dump.json",
		size:    617,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2xRT+sSURTd+yked9Gq8NciiAEJSSIJLfATvMY3Ojj/eu/NiISQ+acobRahhFjWTqKc
FtEilT5Mvje26ivE/LFm6Le7nHvuufec+7iAEELAMW0RDgp0yUO4mmAm4RiUhBADFjYJKHGp2pSYWDfQ
r/EsPGzl4tlx9+0U7IS/SMdjWkSiHQYKAjWiM5OJF+vT8CA+vxGrjVx9lK+ey7fDcDn6X0juffn13e/9
VPhBgojpWL78JOdf5Gwrvr8WwSR8PxCrjZiMw+VIzn05Wic6xx8f5CD4+eRp9hqDeMSIDVzPoLznnF1V
63fuZwewy9s2jZvQtQ0tb00jlFgqidz9CynuudQABTLsJDOPXIJ2HL0JCtx7cO3i4uYN+Nvsx1U//QUl
j1zCeO4dDubt5HAExTTdIruluZZaKldq1bqCHafBMSdXmq7p3LYtTW+VilkTjs14BUdvRgC5hR6hutbL
7TsHBYxT3WpldUzM1egWqGHdKjdN3Wp49K7NeCpa6Bf+BAAA//873kPQaQIAAA==
`,
	},

	"/plugin/json/discuz_admincp_xss.json": {
		name:    "discuz_admincp_xss.json",
		local:   "plugin/json/discuz_admincp_xss.json",
		size:    567,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3SRvU77MBTF9z6F/1d/QStBG1qkSqkqlm4sSFm6IZPeNFYTx9g3rQLqxoZQVwbUmQWJ
gZHXSZ8D1WnB4WOzzv34nXt822CMMSCup0jgwwKv4KjSUiQOftVgBclTBN8+R8KE+c0/1m93GZ+kQoaq
rWLFxkGwG7dtGlOuZwb8vyfKl8fy6blcPZSvd+X6fhwEm/fV5m3trklwjokl9xyVCrW38w3Lc4ozbWuw
yJKobilCjTLErauv42wt1wn44HRbNZzjL+pMiQn4cH5x7HmnXfgsLu1ructQ43WOhmoxKk5x5ZtBx4ni
TMgoyTgNCzQHMZeTBGdYDE+6vdaA0FCz73mtQafjXqMyQyO+/ScGUCPPUYuoqIH3gYEhLeTU3ZNyCrem
QETN/81DjZRrefkTXSEay48AAAD//+Clk3I3AgAA
`,
	},

	"/plugin/json/discuz_ajax_xss.json": {
		name:    "discuz_ajax_xss.json",
		local:   "plugin/json/discuz_ajax_xss.json",
		size:    559,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3SRP0/CUBTFdz7F8w5GEoUqJiQlxIXNxaQLm7mWW1p5bZ/v3QLVsLkZw+pgmF1MHBz9
OuVzGF5BW/9sL+ee3t+5p3cNIYQARj0mBhdmdAWHpRYTI7ilwQoJxgSufQ4i42e3e6Lbmgu8xnlLhUoM
PW/7rfVoilFPDLj/2IvXp+L5pVg+Fm/3xeph6Hnrj+X6fVXdIWlK0jI7FZVztQvyg4kZh6m2M5ilMqjn
CUhT4tMm0vdZdpZpCS5U3Fb1p/SHOlHRCFw4vzhynNMOfA0X9rXYtqfpJiPDtQIVcljmFtDe9XAWJYFM
kfs5mf0Qk5GkCeX945NOs8dk+KDrOM1eu109RaWGB7j5PQKghp2SjoK8Rt21BYZ1lIyre2Jkf5MIYjIG
x1TiL3+zS0Zj8RkAAP//w2oEai8CAAA=
`,
	},

	"/plugin/json/discuz_announcement_xss.json": {
		name:    "discuz_announcement_xss.json",
		local:   "plugin/json/discuz_announcement_xss.json",
		size:    583,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4SRMU/CUBDHdz7F8wYjiUIVEpIS4sLmYtKFzZzlShva1+d7V7AaNjdjWB0Ms4uJg6Nf
p3wOwytoiyZul//du//v/u++IYQQwKgnxODCnK7huNQSYgS3HLCCxITAteUwMn52dyB6rVuBUqaZ9Ckh
yS0VKjHyvO0OO6spQT014P7zrHh7Ll5ei+VT8f5QrB5Hnrf+XK4/VtVdMc0otgydisq52oHteWPGYapt
D+ZpHNS5AtIkfdqg/Zxpe5mOwYXKtFX9Gf2hTlU0BhcuLk8cp9uF7+bCVottmppuMjJcC1QhhyW3gPZ+
HueRDOIUeZCTOQxRjmOaUj44Pes0+0yGj3qO0+y329WTVGp4iJtvEwA1+xnpKMhr7rvUwLCO5KS6J0H2
N2SQkDE4odL+6rd36dFYfAUAAP//nkX4KUcCAAA=
`,
	},

	"/plugin/json/discuz_api_pathinfo.json": {
		name:    "discuz_api_pathinfo.json",
		local:   "plugin/json/discuz_api_pathinfo.json",
		size:    542,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/6SRv0rEQBDG+3uKdWo9D7lrFsTmOhtLQSzW3OSyXJJdN5Mcp6QQgmClloKNpVgceIWN
f15GE30LySbRBOzshm9mfvvNt6c9xhgDEmaKBBzmeATrlRYgCeDVgBVCESBwW45l5MQna2x/qz9im0LL
vvY0K16ui4eb4uK+uDr/fFp+vGb5Kvu6fayJdtNgIMwsAv4fiI8J+tbKsKXSQjf+3t/u8rNlvsry58v2
oojJU8YOwVz5bteZiwZDB0tzv2fbXmx84NCatqqT4B/qTMsJcNjd2xgMhiP4aaa2Sut0DR7HGFEnYC3I
qw5g0OSxE6jJweG2iEm1zWoV0ViUH8QAOuAEjXQXHW4TDERkZDhtcwJBTvkm2OxVyHwZYg3spd8BAAD/
/9wBEkMeAgAA
`,
	},

	"/plugin/json/discuz_attachment_xss.json": {
		name:    "discuz_attachment_xss.json",
		local:   "plugin/json/discuz_attachment_xss.json",
		size:    577,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3yRsU77QAzG9z7F/T38RSVoA0VUSlWxdGNBytINmdRpoiaX485pCagbG0JdGVBnFiQG
Rl4nfQ6USwsJIDbrs8+/z9/dtoQQAhj1lBhcWNAl7FdaQozgVgNWkJgQuLYcRcbPbv6JfudaIDP6YUKS
OypUYux52w12UlOCembA/fNR8fJYPD0Xq4fi9a5Y3489b/O+2ryt65timlNs+b2ayrnamfpGxozDVNse
LNI4aLoKSJP0qTT2daLtZToGF2rTVvXn9Is6U9EEXDg7P3Cc4xP4bC5ttdwmqekqI8ONMBVyWPkW0G2m
cRrJIE6RhzmZ/yHKSUwzyoeHR732gMnwXt9x2oNut36QSg2PsPwwAdCAz0lHQd5g7zIDwzqS0/qeBNkv
fUFCxuCUKvzFT3bFaC0/AgAA//8XrBN6QQIAAA==
`,
	},

	"/plugin/json/discuz_focus_xss.json": {
		name:    "discuz_focus_xss.json",
		local:   "plugin/json/discuz_focus_xss.json",
		size:    556,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3yRsVLCQBCGe57i3FpJIIRgasbGxhka2/WyBxlyJN7tgejwDLYWjrWNnaWvA8/h5ABJ
HMfu5t/d///y56kjhBDAaKbEkMKK7uB8r2lihHS/4IUFaoLUP8e5dfLxTDxE3VCoUjrbtSslbieTw7Xf
MqTRzC2k/kC640FgGTmXQa5xSoHjvAhOHtuPl+3r+1WBdlb77b6ed59vTdeCllR4jqih8ro6wv2iQMez
0vgZrMpCtQkVGVpIqiFPn+pnzhSQQmPbq3JJf6jzKs8gheubizAcJPAz3PjX5tCooXtHllulVsizPbeA
/3ppUlel5THWf0cAtBKWZHK1bgUciwGdxU0TjSzrZJC9ISZy2BtEKrwcDZI+xf0s60UZjeK4n6hDQmfz
HQAA//+QCFpKLAIAAA==
`,
	},

	"/plugin/json/discuz_jianghu_sqli.json": {
		name:    "discuz_jianghu_sqli.json",
		local:   "plugin/json/discuz_jianghu_sqli.json",
		size:    614,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3SRv47TQBDG+3uKZSQQyBvwLv4TLEU0VyCgOMQTbLxje3X22uyfhAOlpKalQHRI11BB
yeskz4GyyQVbynWrb76Z+c23ny8IIQScMDU6KGCNS6AHrUMnoDgYgqBFh1CE56Wypf/0gLxWQtevPLlq
fa00ef/u7e737fbLz+OM4DXYCXNtobi3bfvr2/b77al59/fr7s+P8YgWV9iG1WykupvhjufsYuFd05vg
gHXfVlOoCg3qEvdc/28MNW9aKGDkDmq5wjPq9aAkFPDmahbHyRxOxU14bY5RGvzg0bpJmoNwzYGewLOq
N77rlLWq10+HZniptMSPC9v060dKLnjykMdCy4gteOS16nVkscXSRYxy2sn0cR7HT2hCU5rRnM7pC8pi
ythsNr556K27FPtPJQATvhUaVd1M8O7CBeuM0vV4TidcuUcHTOcJkxVnWSZlwhOR5oznCX8ueZ4tl3hc
crH5FwAA//824x0MZgIAAA==
`,
	},

	"/plugin/json/discuz_member_xss.json": {
		name:    "discuz_member_xss.json",
		local:   "plugin/json/discuz_member_xss.json",
		size:    565,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3SRvU77MBTF9z6F/3f4i0rQBopU4api6caClKUbctObJqqdGPumJaBubAh1ZUCdWZAY
GHmd9DlQnZYmfGzWuR+/c4/vGowxBiTMBAk4zHEEh6WmkATwssEJiVAI3D0HsQ2y23+s27phCtUITUtH
mg19fzvtugwqYaYW+J8DxetT8fxSLB+Lt/ti9TD0/fXHcv2+qm6ROEPpuJ2KSrnemflGFRlFqXE1mKcy
rDsK0WAS4MbU/jRXy4wEDpVupwYz/EWd6ngMHC4ujzzv9Ay+igv3WmwTNHidoaVaiFpQVPpm0N4ncR4n
oUwF9XO0/yORjCVOMe8fn3SaPUJLB13Pa/ba7eoxOrU0EJtPYgA18AxNHOY17i4vsGTiZFLdowQFG0+g
0FoxwRJ/9ZNdMhqLzwAAAP//MapGiTUCAAA=
`,
	},

	"/plugin/json/discuz_misc_sqli.json": {
		name:    "discuz_misc_sqli.json",
		local:   "plugin/json/discuz_misc_sqli.json",
		size:    583,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3RRuU7DQBDt8xXLFK5CiEE0liyESGgI4ggdQspgT5JVvLbZHecApaSmpUB0SGmooOR3
ku9A3hzYUuhWb97MO/apIoQQwKh7xODBiO6husQUMYK3JFggRkXg2WdDmiB73BHjg9q+UNIEtbSfivZV
a/E1mz9/rE5YqiaFemDA+29r/vk6f5ttdhc/L4vv9+KFiIYUWWG3gPIkXbvZqosZ9xNtGTBKom7ZU5c0
xQHltv4S2lmmI/CgwLZoMKQt6CCVIXhwdrlbrx/WYTOc2td0VaSmh4wMl7pMkftL9wL21lUcqST0DSM7
Seqzpjh0xiryXUeR7pHvOnlmc+ve+YhYzJMmhhuYf5cAKGkPScvupCS9Lg4Maxn3incUcpDbgnaz1Ty5
ESFOWCqqdhCxI47bIjcnDctAnF5fnK+kKtPKbwAAAP//cpEI4EcCAAA=
`,
	},

	"/plugin/json/discuz_mp3player_xss.json": {
		name:    "discuz_mp3player_xss.json",
		local:   "plugin/json/discuz_mp3player_xss.json",
		size:    568,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4SRP04zMRDF+5zC39Qf2UVL/m0d0dAgpaGddcbJKnZi7HFCQHsGWgpETUNHyXWSc6B1
EthFSHTWm5k3v3l+6AghBDC6GTHksKEC/h80Q4yQHxqisERDkMfnuPRB3v8Td1k3FcZmVuOWXNdvlLiZ
TI4OsdORQbfwkMchGU5DiWfkUialwRklgUudtH12b0+759dLjX5ee+4/HvfvL01nTWvSkSdrqLy1J8gf
JBh4vnKxBpuVVm1KRY6WkmrQ75NjLTgNOTS6oyrX9Iu6sOUUcri6PkvT3jl8Fav4qo7JOroN5LkVrkWe
H7gF/JVNk9yuPI+x/ikB0NqyJleqbWvJKRww017TxCDLejuoQVb0L9IejopigGmfpMRRVig5HKnhdHi8
qOpUnwEAAP//mr+i+zgCAAA=
`,
	},

	"/plugin/json/discuz_post_xss.json": {
		name:    "discuz_post_xss.json",
		local:   "plugin/json/discuz_post_xss.json",
		size:    597,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3RRsU7rQBDs8xX3trAeUghOUBRhyaJJR4PkJh26OOv4lLN93K0TDEpHh1BaCpSaBomC
kt9xvgP5nICNoPJqZrwzO3fXYYwxIK7nSODBCqfQrbEEiYNXCyyQ8gTBs+NYmDC//cdGvQFTmaGeihWb
BMH+X6vRmHC9MOD9IS9fn8rnl3LzWL7dl9uHSRDsPja7921zh8QlSut52kCpUIcgPzx5TnGmLQerTEbt
PBFqTEOsIn2fZblcS/CgobZouMRf0IUSM/Dg4vLYdYcD+CLXdlrv29N4naOhVoGKU1znZnBy6OGchySy
1NeoZOFEYub3Rw5Vn+FZ38Eb0tx3LGnyaSLIL9A4Io1kxus55ulM4gILv0to6P/IdY+ad1dGY169JQNo
ZVyiFlHRinioFgxpkc6bexJOYRUfEjSGz7H2vWqY1ss7688AAAD//+dC8YdVAgAA
`,
	},

	"/plugin/json/discuz_shop_sqli.json": {
		name:    "discuz_shop_sqli.json",
		local:   "plugin/json/discuz_shop_sqli.json",
		size:    658,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3xSPW8UMRTs8yucJ10EkeFs78eFlU406aAI4hf41m/3rOyHsb0XBXQlERVUSBQIKkQa
RAElf2ePv4HOdwm7UpTOmjdv3szIbw4IIQS8tCV6yOACF0B3WI1eQrYjBKCRNUIWnqfa5d3rQ/L3+8/+
3VX/8ar/+p6cVV2pG/LyxfPNr+v+7be9UFiwWEt77iC7f7f/8an/fH2rsPnzYfP7y1CnwhVWwQQfoP7S
3Di787rs/LK1gQEXbVWMnRVosclxa+5/2jDrbAUZDNgBzVd4B3putIIMnp09YiyJ4Ha4Dq/1vlSLrzp0
ftSrkX65c09gakIRj83SPNVqvkojt2xNVratckdG5nPdFO1RqdWcTwSTjZoIxudiIljX6LaZCDY9PkwY
Y8xhhbk/nm4JVNCIxjShKa1V8mDG2EN6Qp9QzijnlAvKI8rjYSumdf5Ubj8AARglWKHVxeUowE394LzV
TTnUqaXPt+EAk5OYq0LwNFUqFrFMZlzMYhEpMUsXC9wfOVj/CwAA///8+WiHkgIAAA==
`,
	},

	"/plugin/json/discuz_viewthread_xss.json": {
		name:    "discuz_viewthread_xss.json",
		local:   "plugin/json/discuz_viewthread_xss.json",
		size:    546,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3RRP0/7MBDd+yn8u+mHBG0k/klWKUs3FqQsHVhMcmms5o+xL4kKysaGUFcG1JkFiYGR
r5N+DhSnhRjBYp3fO99793w3YIwxIKHnSMChwmvY77AUSQDvGiyQiRSB23IqTVDc/mMnQ4/NfH/7xFIa
U6EXBrjbVUqsKNYowqGKFWten5rnl2b12LzdN+uHme9vPlab93V/UoIlJlbwsIfSUu1c/FAWBcW5thxU
eRK5riLUmAXYGvveyXKFToBDr9uiQYm/oAslQ+BwcXngecdH8EXWtqq30Wm8KdCQk54SFHe+GYzcNM5J
hmdXMJqMCQ1N2uP/qeftjUf23t9D5Yamov0YBuBolqhltHQkd1GBIS2zeX9OKiho7fwt2g0f1J8BAAD/
//oRkGIiAgAA
`,
	},

	"/plugin/json/django_urljump.json": {
		name:    "django_urljump.json",
		local:   "plugin/json/django_urljump.json",
		size:    744,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2ySz27TQBDG732K1ZyJNy2NqCwuiOQCqVRFCveNs4lD/Y/1OqGgSAZMiUSk9AghRSBF
ogfUIEjV0BhehqxtTnkFZCcBGzjtamb2+3Z+M4+3EEIIOGFNykGGDq3BtVVMp5yAvCpIAgbRKcjJtXif
GE0T3UQ7Ul7aQ4v5PPAG1Uo5uvwSffsY+INg+natk9QzqhN2aIOMQIzOLMJV4btiPF3MrjCmD4luaVRS
TD0cesGz5+L4YjF7ufT7K5vg83vxZCjGXnhyvPT7YuJHL6bBxSD60BOvz6Lz8WJ2Fb45D4eeGH0Sp27w
ahLOT8Xka3Q5Ed+9pd8PRm447/103wW9k//+9Yf7NP1djbaplrR6PRXlR9am/2qlfKe6f5B+QxyumizJ
Q8fUGtn2G5RRQ6ExgT9Ek5zDNJBB5dyyZYybLa46tRgFbjua6tQ2R00za1gnNqcM1xMs+Pa9Um4nv72X
294t3NjFldKt4n5JeqTmFEPS6yn/xEdpU5Ah++bvmkOrVQcZ7h7k8vlCAX4nu8mtu14MRh841OaZ3YhH
umKDAONOpyOlpppGYZk2L5J4sxBARrZNWatxlFHdEAebs5bRTOvohCuxI5RNhfCWacjoH1+8Ntjqbv0K
AAD//+5NwlroAgAA
`,
	},

	"/plugin/json/docker_api.json": {
		name:    "docker_api.json",
		local:   "plugin/json/docker_api.json",
		size:    647,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4RSy4oTQRTd5yuKuzapbHRRu2GShYgw5A+qOzfpJl1VbfWtHmYk4JMZxBmXIkTwwaAo
zIAvBAf9GNNtsvIXpKsnY7cbV13cc/qcOufW7Q5jjAFJO0UCAbsYwJV6ppAkiJrgB1oqBOGPAxPO0LIR
KkPItnaul4t35fFh+fz+6vTH+unphYbnWlTSzjIQ//+teHJWnJ2vDj4tv73+9eJu+fHBevHh9/nj5deT
9cHRJVoujopHL4tnb1ev3hcPT5bfP5fHb4rDLz/v3GsaJ5hj4i/cb0xpL92kGG0Pm3zpKDLWY7Brkkk7
xAQt6hCrHH878ZizCQiIiNJMcD6NKXJBLzSK5y6JXLD5BIkJuJIZoeVjXwR3uvaM93HctSHy0XBrcHPY
24+6oe6pceMG3inMEQT8O52l8RgE3Njp9vtXr8ElOPen+cU6Ld5ymFFro6mkqO6CAY/1xDQjpyajgaze
AANoSeVo48leS2nTKmRkYz1t6ihJYeUC20aTjDXabOS0rli1amfe+RMAAP//W46lkIcCAAA=
`,
	},

	"/plugin/json/drupal_geddon2_rce.json": {
		name:    "drupal_geddon2_rce.json",
		local:   "plugin/json/drupal_geddon2_rce.json",
		size:    876,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3RSX2sTTxR976cY5scvKJjOtmpbFhYpTQQRofTBlzYsk92b7Nqd3XV2ZmOVQJWKrdb2
1T9BrFoa0NKXKAWDfhizm7z5FWR2E90IPs3MvffcM+fc+2AGIYSwoLwJAuu4BXV8KY8xEBTreUEW8CkD
rGfXCpch9VB+NMG2Ax/No9H3zrD7bPD1/fDtw3TvZHS0n/YP096bcccMyYFRvhlhHeEFskiWhnu7aefT
8NXO9YAztLx6Y3B+mpy+SDrdwfl28mHnXz1/9veTw7PkrD960ks7z5OnR8nL7vB1Lz04Hr37mDw+Hnz7
nB6cJLtffmw/Kn7Agxi8TIZWiIqtcKJtbaVarKdSOAHPcrgVeI1pMQ3g4Fug9PxxKstJ7mEdO0KEkU5I
0xWOrM9aASOx9BxZnxx1L6gTRiMBnNiZnWTldrU8r80tlRcXNI2sVZcrt6qz952y5c8yu0Cf0VgxYB1P
Qf4u2QxdG+v45mpZ064u4t/JdnZrj8fN4a6ESExNPKTCyV1BmMgIOOHQdNVfr4EHDHxhhpSDLyKDWlYg
fUEYdT3y//zlmHoSSvQOvWc2As6MuZLZ4jQMgWdvKoxcralKip6GQSQqVK0ewqrSdG1DUZsT6gxfMgtw
Y66kaNf/U1iTg28Dr63XjJhy05YsHGfVjGuGWj85CeWPmiGU8ik7YuBuY2vKjcmO4Ehw128WP82osJRT
49SFKxfRBlZNN/C47Ux75lcAAAD//48UPxVsAwAA
`,
	},

	"/plugin/json/elasticsearch_unauth.json": {
		name:    "elasticsearch_unauth.json",
		local:   "plugin/json/elasticsearch_unauth.json",
		size:    574,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2yR32oaQRTG732K4Vy36E2h7F2hhUKhFFqvy3R71MVd3c6OihShrW3dFo0QyD/YBAwI
kj8aEhMCWeLDZGfiXvkKwdk12Q25G77zze9855zvGUIIAU5ZETlo0MAv8CzSLOQUtMighAq1EDT1fGNS
hxv6R6RMLxHpHcg1V+625+NZuDWOAcrI0KKs7IBG4JFLTPx5Zyo3TmRvHMwG8udEnv0OvdOF3w3bI+H+
vf3nSu9Iupuyvx5cXYjjbeGNpN+X072F3w0uh2GnJ/qTmOP1xP+B2BnN9w/Fn2FwfX7z41cyiIl1NFX6
XELlTXs1Uv79q/ynt8kvtMZLVabK0KiahfRcBWRY0XE52sOOVK3GTNAg4VaqXscn1LJtfAUN3n14nsu9
eAn3xZZ6teJTMPxWQ4enrmFTXoqiE8h+1ilPxrOrDn9Nl/cjAClUHZlRaKZIqyWAw5lRKSY5FuX6skvU
IWtRhyOLgZlW5i4AAP//sc0XKz4CAAA=
`,
	},

	"/plugin/json/glassfish_lfr.json": {
		name:    "glassfish_lfr.json",
		local:   "plugin/json/glassfish_lfr.json",
		size:    626,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4xRT+vTQBC9/z7FMtCbzUbRg3sTtCL+QcQvsI2TbOhusu5OUosURApCQXorKF68eetN
hHwcm+rHkGxaTTz9LsnkvZk3b17eXjHGGJB0GRIIWOIcbvSYQZIg+oYAFNIgiFA+1NL7We4VOzbNabM7
7T8cm++/D02725/nQ59DI93Cg2DQ7g49f/rysd1+bT99O/7Y/vq8GQr8fPd+OK2xRh023hqgtLIXG09m
L4b9siJVusDBstTp2EmKDosEOzP/jgpc5TQIUETWC86znFQ1j5LS8LrSqppfXuQQuZGe0PGsCyDNveK3
o5tRPNgUFJMaQcD/6MLmr0DA4+fTOL5zF/6S61Ctz7k7fF2hp1H0VpLqb2bASaFB/vTBy3vTR89mfJLE
E4n987ofw2Rs6em+7P41Axg5qdHl6Wpk5BI+eHJ5kQ11jKSkMwlWJguZ4VRam+gcC4reGH1Wvlr/CQAA
//+MJ+p5cgIAAA==
`,
	},

	"/plugin/json/hadoop_yarn_resourcemanager_unauth_rce.json": {
		name:    "hadoop_yarn_resourcemanager_unauth_rce.json",
		local:   "plugin/json/hadoop_yarn_resourcemanager_unauth_rce.json",
		size:    784,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/5RSTW/TQBC991dYeybZcOFgIaSoVKqEiFBEhThunEls6o9ld+00oEiFUlpCaOCEoEFV
UKpWIDUHPlSRtPkxeB3n1L+AvG6ow42Tx29m3nv7NE+XNE3TkCCsDgLpqAEVdC3FHBAE6emAAlziANJV
uUqqnke1h8VySSsD93xmwF3ikjowLep9ifZ2o09b8clk9v4El5dXLinVKgOHsHWO9P9iuRh3ZHcYHRxO
e69n+y+n54Pp/qnc/hZO+tGz4cW4M9v8GE92ou7b8NcgHI1kuy/bB/HWmewOZe846r2R7X542o5eHcX9
TjgaRS+68t1ZOBokzMNxvPM9nZEfjuPPX+X2YXj+I9o7krs/f28+z/q3IQBbxVDIoKJJ59mslYpr91ez
K8QXpsdUGzU8u7YYRw0YuAYkiVyFrXo+s5GOTCEo1zGuW8L0K3nDc3Dg26ZfmX8EA8AO4QIYNlWk2HdT
TesJVHNNwtyMpKI2AkA6+hddp1YV6ejOvVyhcKOA/jZbqmpdHgaDxz5wsXAblAgzfb+GcIPj4Do2bF9Z
IpRy7EIjRyi1LYMIy8vaQdTj4jZJbk1DaEEoAGbVmgs685wRF8xy61kehwgj8YBuPiIBWbYJ5yXiwK3k
byPf4HnG8w+gUrxysbJhAFV2Utml1tKfAAAA//8RYSlXEAMAAA==
`,
	},

	"/plugin/json/joomla_3.7_sqli.json": {
		name:    "joomla_3.7_sqli.json",
		local:   "plugin/json/joomla_3.7_sqli.json",
		size:    646,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3ySvY4TMRDH+zzFaopTIiW763weliIKoAEKEBINQsi3nk2ss9fGns2HUEpqWgpEh3QN
FZS8TvIcKE7u2E1BN5r5/2b+M/anTpIkCZDwCyTgsMYb6J9yBkkAPwliohIGgcfwubVGi2SUztI8efP6
5eHX3f7zj8OfL4ff38981Hk0wt8G4BfI/ufX/be7/4AaV6jjMNbI0tbdO3hgm5SoaWl9VMDa6rJtpUSP
VYFHN/+2irXaa+CwJHKBZ5kTDn0aEG/qRWr9Ihvlk6zRKiLFCoHDk7fPBsOczQbXj9jsUnLrlAQOL14N
8nzK4KG4i9HufGaPH2sM1Lq0E7Q87ZlApiqJm9Qt3WPrSNlqXljzoVSoZbhaKVzPz7EWW1vT3Fgp9JVW
gd6VtdbWS/SqWryf104Kwo3R3XwzHPULWxWCuqxv5KQ7y/Ner896zYM5G+ipOP6BBKBleYVelduW4/uX
gUDHac0+RlBx3AZwcj1mshyy6VTK8XB8btrZdf4GAAD//29U4JWGAgAA
`,
	},

	"/plugin/json/joomla_contushdvideoshare_lfi.json": {
		name:    "joomla_contushdvideoshare_lfi.json",
		local:   "plugin/json/joomla_contushdvideoshare_lfi.json",
		size:    671,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4yRsU7jQBCG+zzFauq7OHfFFZZONFTQ8AZoscexyXpn2R3bilA6JMp0EQWipkE0iMY8
TmLxGMjrJNgCoUhbjP6Z/ffbf65HQggBLO0UGUKo8AJ+dVqOLCHsBrygZY4Q+vKEKFdSRKS5cGlcZjGS
S6VFsa7r5mbZrG7X9ev7c71Zrpq3ZfPysHX1ty3m0s4chD8ZbZ7uNvePh9gpLFF5sD89ledmR3uIiSw4
JesvQEUqGfImaFFH2CJ/BuJ7hVUQQm/aq1GJ36gzk8UQwunZ78nk31/YNxe+Wmxzt3hVoONB9EZy2n1G
QBBRbkijZteW51+zC9I4UaVRco42iKnSimQ8Nqk5Sv6Px0F3ItJJNi2s5Ix02+z/2JDjY9nuXwAM6Eq0
WTIfwO2SBsc209O+Ty45asGBUxSX+10PH/bbl5kW7VBFNnbbJ0eLjwAAAP//YhyIpJ8CAAA=
`,
	},

	"/plugin/json/joomla_departments_sqli.json": {
		name:    "joomla_departments_sqli.json",
		local:   "plugin/json/joomla_departments_sqli.json",
		size:    599,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2yRP6/TMBTF934K60pFIDmQuPlTRaoYoANQFVBhRm5800aNY+O4LRXqyMzKgNiQujDx
xvd12s/xVPfPS6Ru1rnn5P7uyfcOIYSA5WaGFlJY4xToSZNoOaQngxMqLhFS93yrlCw5Eai5sRIrW5PJ
x9Hh/27/4+8573wGJTeLGtKbkf2/X/vfu2vwcP/zcPenGS9xhaVbGTRUu9EXjptL+dLOlXEOWKsybwPl
aLDK8Mj0eJubLU0JKTTcTs1WeENd6EJACu8+eL4f9+A63LrX9lyhwa9LrG2rRc3t/ERP4EVRCfz2XM/1
S6VtoapBpuSXRkVPCjHwgi7zP4/fvB93mT8ZjoavPnWZH1ApoqeJ7z+jPRrSiMY0oX3Pax6rVW1f8+Nf
JAAtsBWaIt+0uC6tQm1NUc2a35HcZkdmwKgfBiJnQRwLEbKQR0nAkpD1BEvi6RTPSzrbhwAAAP//EkqS
FFcCAAA=
`,
	},

	"/plugin/json/phpmyadmin_deserialization.json": {
		name:    "phpmyadmin_deserialization.json",
		local:   "plugin/json/phpmyadmin_deserialization.json",
		size:    792,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2RSUWvTUBh9368I34NPa5Nso7ArPoytTzIcexEhILfpbROW5F7v/dKujkKVSTuo5EWq
yBBFhz44+iIyzMAfY5LVJ/+CNG23dHvK5Zybc88533e0ommaBkhlkyEQaLMarM4wnyEFMruQAwH1GZD8
KBzhd2jddwNN2dIVqHTFMBRl4QgtjV6nv6J08DYdjrLLKPvxYS6Z/yqZT+WBArKkslY+vDoZZKffk4vz
9PxdevotueilX47vav27HP7tvZ/87k/GZ9dI9iZO+/Gk9yqNxkl8NhnHaTRK4jg7jrJRP4l/ZoNRdvJ1
8mk4A5P489XHF396L4vOPNZiXh7QKKDYEYvU+9vV4n0aosNlzkGbe43llA0mWWCzadCbDnMulB4QcBCF
IrredNEJa2Wb+3or9JywtvjUPF7TfaqQSf2mKf0x50/CoLRmmJWSubm5sb6u71e3dnar5edOyQ7Kfr3g
I3/PbjEgcBs9EG4dCDzcKxlGZQOuyW5+6s6XQLJnIVO4tAeCojNrRAP9zviLLQiucIdO10gDaqPLgwfI
FN6zedBwm6GkOfSImAaxYG936+l2TlhATHKkSIVYoHgobWbBqiKmSSzQGdq6oEq16xbc78KS2xaTbqOz
ZHYxPlAo3aBZdOdTtKdBQHKO5JAYxJjLrXT/BwAA//8WDGbnGAMAAA==
`,
	},

	"/plugin/json/thinkphp5_invokefunction_rce.json": {
		name:    "thinkphp5_invokefunction_rce.json",
		local:   "plugin/json/thinkphp5_invokefunction_rce.json",
		size:    886,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/1xSX0/UThR951M080B+v0Q6C3FNbLIxRkg0xoQQ31iyme0OtNm2O06nVTQkqIAgsAsJ
GtGNcQXCJkQ2yB+VFv0wdqb1ia9g2u5q16fennvn3nPOvU8GJEmSAEN0BjOggIe4DK6kmIkZAkpakAAW
MjFQkvC+plvV8dvjeSkv5+SREZiXh+WR61L0oxm2VwNvJ/zwVKzsR6014TfEyftuz+QtxSaiVRsoEgi3
joLzuvjcEs0V8WknbB3y3YVwY0nU9/nyGd9u8431S3+Nd/zoxQlvtsOLzfBgO63n/jzf6HD/nC+fRV86
4dZR+HZBPF/kS6fB19VLf5mvH//y3kSHuxlwhTc6gbeXUgs8Tyw0xOtv4vjVpb8WePVovjsr1cE3LwJv
N6sjJtPopDWiuc5ftvh2O3x3Iup70ccDvrgXfD9Nyf+cf5YVbWAXG4l5uQzKZknP0YlbY9l65DCtRpMc
IJrOtJzV7+E0pthScWzj3xUlOYcaQAEaY8RWIJzRmeaUZbVmQtcxNKfc+5SNWhmayGaYQhavk2gE5oeo
iuHE2M3Re2PyY21ItWSzkhmcDFBdDBTwL1olegUo4O74UC53LQ/+JOeSaK57VBQ/cLDN+u6KIKalLkgA
6lYFP5KJRm7YBXgn/oHFYsKvWESEQN1ya1U87Vgq02vWYC8oqMgwSo6NaSmGSohSNDvoImpP5qYKLqKl
imOSFBiempwqsJhFxlFSs9koii9eAqCPsoupPj3bx7i3N2Azqlsz2T4mYmqsppv67+r/UhHEw4q9tgNz
A78DAAD//5odKCF2AwAA
`,
	},

	"/plugin/json/thinkphp_5023_rce.json": {
		name:    "thinkphp_5023_rce.json",
		local:   "plugin/json/thinkphp_5023_rce.json",
		size:    901,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3RS70/TThx+z1/R3Avy/SayDgwxNlmMkUUSJeBE3wBZuu7YNVvb83qdgiGZOoTp2EhE
EnEhTFyYUcQfiJAu+MfYu5ZX/Atmbaedia/u8nk+P5/neTggCIIAqExykAIJ3IcZcCGIaZDKQAoS/IAu
axBI/ncaqXp+anxqVBiNxWMjFwXvR8NtP3fsXXfnEa/sec0q79T54XbYzC8iUJNJ3gSSANjyUVDo2C1W
WXO3ym5llTc+OMf7552qV/vO6psapMjIultlvnnCv750jvf5lyZvVPj+rtv8yN6W3fWnAcTW1847VXbQ
8VYO+YbNVmyvtMzqB47d8j49cTfaKXjPgiZ1P9uObfNyPSw7OeLb5bPSDlt95260z16cnneqjl3zSmGv
fx3VHVY/COc11tizJnvVdl8f8lrLe/OeLbec02+8tsdWj36WHkcZKMAiLPgUxiNRuoB7vKauJaP5skWR
QXwMYKRSFNf7CZ2HBOoK7HL6Rygfs0gBSABRik1JFHMqRVYmphiaWLQKyMr0nkzByIiabFJIRNoVFSMs
BtIMEQWKqeTVsYlkbBENKXpMy0am+1OUIgQS+Duax2oWSODG1FA8fuky+A0u+b+l0F8kEKXPYlimKKBC
AKKqZ+GDGEb4iplQZEwVJEevx4ZJx+SuRwWQDsySSKcVQzcpsRQ6OK8WKCQzc4miTNJZS8ODYVIO0kET
kiIkM6nkrTvJ29PpieT0+OTYXAJfVw28eHcyrw7fBH3bFiFR5xf6lu3pBkxKVD0X3U2TqdI9JIT+Gx75
X5gF0e6zIOw/sDTwKwAA//8GrC29hQMAAA==
`,
	},

	"/plugin/json/weblogic_debug.json": {
		name:    "weblogic_debug.json",
		local:   "plugin/json/weblogic_debug.json",
		size:    729,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3xSwW7TQBC95ytWcyZ1qFBVfG0rIXFBHMgR2e7ENrFjs14nqlCkihZRlTTJoVQUEkQQ
lUKlkguBSDHiY/Bu7FN+AcWbgHPpyaM3z+/NvJ0XBUIIAaZRExmo0EAd7kjMRaaBKgkZUNNcBDUry6g7
nmkbJJ5OxXFHXLyOpz/iyWkcfRJRR3z/uBTJyBRdjVYDUAmkr85mv77FkxveHc3Oh6SMOhG9M346EOM3
yehtOhjzbnsetUTvWrRPRP9o9v44nnyJJ9fpYJz2P/Obd7w3lK7Sz0QWWOg40ncetfjJ19n5MBldSYR3
RvH0SnLlf88CXw48j1rJ7w/JYStp/+SdCzkIvxyK/lF62f1z+DK/hYN1dLL1SzmUHfirTB7v7OX5Wsgs
j2Y9aHhOZT2RClKsGbgI5X/CWS+kDqhgMeYHqqKYNrNCfcPwXKUeOlaorz6MIiquFjCkSmP5GsrOk73i
ZunudnFz+/69nGEmbNQRVLiVUvXtfVDh4aNiqbS1Bf+azaxqLg+D4vMQA7Z2G77GLJkDAaURPA2ZoRhe
rWKbG/tefnXfC9iutrgsArAmW0dqVw7WVFfpQsCoXTPzOq7GjIUjlD1aJQ88F8muTZeKhWbhbwAAAP//
/gPsltkCAAA=
`,
	},

	"/plugin/json/weblogic_ssrf.json": {
		name:    "weblogic_ssrf.json",
		local:   "plugin/json/weblogic_ssrf.json",
		size:    830,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/1yST2vbTBDG7/kUyx58ed9aTikOCEShlFLoJcSBnlerkbSNpFV3R0pCCTjBTVswmEAO
hZbeAmnBmEBpDXLph4lku6d8hSLJru2cdud5Zv/8ZubNFiGEUGTKA6QmPQSb/l9rISCjZp1QCRELgZrV
9iXYgfQEJ53O3rPFgcpQEDJ1oKm5ysnHw2L4sfh8nY+7+fhbeWI6GUy/f7mb9Iv3X2eX1/PRVa0Ug1Ge
XRWDiz/d0zzLpr3B8/393fno5/Tm7G7Sn//+NO/2p5dZ8S4rzt/Ofl3k46ECR+jb7qnLNHJPzIYf5r3z
YnIzy3p59uO2e7b+vQBSCCqG7TUVj+Ml2H0elqAvVWXSQxm4m6wuKIg4lLirOlVeogJqUh8x1qZheAL9
xG5yGRppEviJvVxQARgh0wjKOFzUy9Barb9T3cdToCa9rx7EwqEmfbH7oNVq79B/5km1O1k0UsHrBDRu
9DJm6NfIhBqJ4wg4igOpQBkdYIr7u4kdCL4HntCoBOjmKx0/Vo6sXaschQYeYR2WkaUdd6UcwLG1ilyp
rIaGoFyfJFpEoPV/geQMhYwaNkadxA4FWnV2Q8agGEplleUzDWP74U6z1Ww1t81H7Xa7vd6CWGp8yso5
JZRuQKeghHu8wbxsMy2RIm/9npAhL+tBuUwCh0QSCZdRBByJTEGRcgwJSqJBpaAWL22d/A0AAP//gIoF
Hj4DAAA=
`,
	},

	"/plugin/json/wordpress_cmdownloads_rce.json": {
		name:    "wordpress_cmdownloads_rce.json",
		local:   "plugin/json/wordpress_cmdownloads_rce.json",
		size:    610,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/2xRv+vTQBTf+1ccb1IwbRrTpAREpHUSobi4dLnmXprQXO68e0ko0sFREFwdRBQHXdzc
9M+x1T9Demk1+fLdHp/3uff5cS9HjDEGxM0WCRJocQP3OkwicUg6ggMqLhESNz5XRmiD1rJUCtVWpeLC
smeLx5fHjmRQcrOzkHT8leO32rO11sqQp8vaegatVpUtGvSoSHdInt1bQsl0WW+Lil2vPyLiaS6xorHO
NTt+e3d8//XXj8+/P746vf7y59Ob08+3p+8f+volNlg6w34Ppb2+prjhl9eUK+N20KoyG2bJ0GCV4jnO
/07crjYlJNBjOzRt8BZ0pwsBCTxZeb4fzeHf8uCmw6V6gy9qtDRoX3PKO98MJr3WJw8XT5cWuUnzB2sY
SzG7E/v+3fG6rw1aWVry84cygIFWg6bI9gOpa0VgyRTVtn9HckrPNgBn83AqsmAaRUKEQchn8TSIw+C+
COJos8GLyOjwNwAA//8UAmGiYgIAAA==
`,
	},

	"/plugin/json/wordpress_dzs_videogallery_xss.json": {
		name:    "wordpress_dzs_videogallery_xss.json",
		local:   "plugin/json/wordpress_dzs_videogallery_xss.json",
		size:    644,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3yRwc6TQBDH732KzRyIJiIYDYmk1EsTD16akGhjvKwwhbXArrsDWE1v3ozp1YPp2YuJ
B4++Dn0Ow9JWMN/3Xcjwn2H47W8/zRhjDIjrDAlCaPEtPBiyEolDOAzYoOIlQmjLV1KnK43GsOXr2H0p
UpTPeVGg3rF1HJ832EmNJddbA+GdH3n8Hf/wUOWKdT+/dd9/dIev3a/P3fHLOo5Pfw6n38fxzgIbLCzJ
41FKO3XB+4+B15RLbXvQymIz5dugxirBHvHfYW2v1gWEMJq2adLgDelWiRRCeLFyfT94Ctfm3lb7s1ON
72s0NNGqOOUDNwOvVW4iK8KKPFXUmaiMl340btPLygZZV1fP+iIiXaOTo8hyip74vtOKlPIoeOQ7vZCo
ESVKx8haJxi9AW8xJzS06B/3giC4P/fs+1iJkoaWvL98BjDBb1CLzW5Cf7EOhrSosvGeklPSnwxu+eWw
erb/GwAA//8VXr2khAIAAA==
`,
	},

	"/plugin/json/wordpress_jquery_domxss.json": {
		name:    "wordpress_jquery_domxss.json",
		local:   "plugin/json/wordpress_jquery_domxss.json",
		size:    621,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4RRvXLyMBDseQrN1R8W3/dNYKKaLg0ZiqQV5owN1g/SGcWT4RnSpsikTpMuZV4HniNj
GRKbJp20d7e3u/c4YIwxIOlWSCAg4AL+tJhCkiDahghoqRBEfN4Zt5w59J7hg1S2xCQnVbL1bYWuZlOj
7ufzE0/sd6ik23gQv43+TSbJP3Z4fz68vLU0x8+n48drl6zEHZZRyP8OSrU9q7tYLivKjYs1CKbM+sIy
dKhTbLT9eI21ypUgICeyXnAeQkgyh7iosiQ1imsMno/H4+uraKBDGofTHYKAS3RjiyUIuJkNR6PJCL6L
+/jan5J3uK3QUy98Kylv7THgwQ5Towk1ccpRoecUUFOdFRkhar5Cja5Ijfa8G3LXuDWeprK5MAPobd+h
K7K6t/ycLXhyhV51eZSktBEG621zQB4PyNtPogqdrP2JfrD/CgAA//+gkFs9bQIAAA==
`,
	},

	"/plugin/json/wordpress_mainwp_login.json": {
		name:    "wordpress_mainwp_login.json",
		local:   "plugin/json/wordpress_mainwp_login.json",
		size:    619,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3xRv2vbQBTe/Vccb7CXWra6lIqKLt1KwZvHcpae7aul0/V0kmqKoVO7FNsdDC0NgQyB
LPkxeLOT/DWynCn/QtBJTiQIWY7H9973ve99971BCCGgqByhAgsSHMCrAvNRUbCKAQ1w6iNYuuwH0u1J
DEPyiTLe75HXRtd4a5gk+7dJr1fZZrW//VUKaYJEn8pJCNYL3PT8b3p0VlXYbRe79fH99ne6uMz+r3fz
07J7cZItf6bLebq4qm7xMEZPWzQrqJqKg++7H5v9zZ9CtkqkkRoHUg9BEnjDuvUhSuQO5u6f4tC9SHpg
QWVao06Mz6ATwVyw4GOv3e2+MeGxOdPVrExd4tcIQ1ULXlA1Lg4g0ElEm7o+4x39tukX+s0QY/GeOooF
3GacqaYXjBj/nEsxia5tNqMQpa0J1ctEEKoPNP9lAlBzEaNkw2nNxCFFCJVkfFTV8alycoPwzmUxYa7d
SoReNqCyVQo3Zg8BAAD//9HXaJRrAgAA
`,
	},

	"/plugin/json/wordpress_sexy_xss.json": {
		name:    "wordpress_sexy_xss.json",
		local:   "plugin/json/wordpress_sexy_xss.json",
		size:    608,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4yRvU7rQBCF+zzFaqp7JcJGIAXJCqGho7HkghQ0iz1xVrHXm91xfkDu6BBKS4FS0yBR
UPI6znMgrxOwEUg01vjMzPE3x7cdxhgDEiZGAg8WeA0HtZYiCfDqAScokSJ4rrzMTOQbtJYFuFyxYJYj
3iDzRYyW+UkeS8VGQbCzcisGU2GmFry/bZcvj+XTc7l+KF/vys39KAi27+vt26ZpmeAcE0d03FBppfeY
3xBETpPMuB4ssmTcxhujQRViRfh1tOvlJgEPGtNODef4gzrVMgIPLvxur3dyBJ/NwlXFLluDsxwtteLV
giY1NwO+0N0wU4SKuHaBWC6VJWHrrHiiuVQRLg/1RJ/J6PQK+HBAaGlYPf71+/3/A+7em0fqzNK5qH4r
A2gBzdHI8arFs88RLBmp4qZPKiisWH//aG3eKT4CAAD//1vbYHxgAgAA
`,
	},

	"/plugin/json/wordpress_swfupload_xss.json": {
		name:    "wordpress_swfupload_xss.json",
		local:   "plugin/json/wordpress_swfupload_xss.json",
		size:    674,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/4ySPc/TMBDH9+dTmJsaiedxkqpvQRUDiAUJKnWAAQZjX0io84LtJK2qzCxIbAghxMzC
hljox6Fd+xVQ3KYkiOHZTv87/+/ud95eEUIIGKZeo4EAKnwFd09agoZBcCqwQsoShMCGzzIlFgq1JroK
i1xmTNzoKiSPJNPR8+Xy7GFrFSZMrTQE3We0yq/jlMtCoKZvNL3Y0L7h4eO7379+7r9/2n/51pofdh8O
P74ed+8XTx8cd597D+4nWRnjE5bg/AW8dGrODI8G6GzjcHCnilORVTdrZ9tGc+8ek6jMgK61pk5dU9od
XWKJ0q487Khmk7cc/lmVFSbKlM1BlcmwjyFEhSnHhsRfqjZXKAkBdKqtykv8j7rKYwEBPF5cu+5kCJdk
baP6fDyFbwvUpne/nJnoNDeBW/LvLpBn2jxkzZ8gAL1mJao43PR6tYwgEaOuSdLco3EYMo+POZ/4UyEE
90dTd+axseuF/pTNuOefO1zVfwIAAP//leBVT6ICAAA=
`,
	},

	"/plugin/json/wordpress_wpml_xss.json": {
		name:    "wordpress_wpml_xss.json",
		local:   "plugin/json/wordpress_wpml_xss.json",
		size:    573,
		modtime: 1641259650,
		compressed: `
H4sIAAAAAAAC/3SRsUoDQRCG+zzFMoUoqAmcIJwEGzubwBVJIYT1MknW7N2ts3MXg6SzE0lrIaltBAtL
X+fyHHJ7ie6Jdss//8588899SwghgCVNkCGEOV7DYa0lyBLC2uCEVCYIoXv2Mxr1CK0VfZNo0dP5RKVi
EEXbz85EmEiaWQh9/9zzl2/P5ctruXoq3x/K9eMgijafq83H2m+isUDtpgaeyguzQ/k1VOY8zcjVYJ7p
cRNojIRpjBXTz2KulpOGEDy3U+MC/1BnRo0ghMveUadzegLfxaV7Lbf5Ed7maLkRoZE8rbkFtFU6wrtj
MzXnKtZDGbPK0i5hUuk0NJnJzV59mO6NLKSNSRkOGS3vB0FwcNZu+8uZzPKFrE4mABogBZIaLxocu/zA
Mql04vdJJMcVI1zBf1Pr7q3lVwAAAP//5VOs6z0CAAA=
`,
	},

	"/plugin/json": {
		name:  "json",
		local: `plugin/json/`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"plugin/json/": {
		_escData["/plugin/json/coremail_config_dump.json"],
		_escData["/plugin/json/discuz_admincp_xss.json"],
		_escData["/plugin/json/discuz_ajax_xss.json"],
		_escData["/plugin/json/discuz_announcement_xss.json"],
		_escData["/plugin/json/discuz_api_pathinfo.json"],
		_escData["/plugin/json/discuz_attachment_xss.json"],
		_escData["/plugin/json/discuz_focus_xss.json"],
		_escData["/plugin/json/discuz_jianghu_sqli.json"],
		_escData["/plugin/json/discuz_member_xss.json"],
		_escData["/plugin/json/discuz_misc_sqli.json"],
		_escData["/plugin/json/discuz_mp3player_xss.json"],
		_escData["/plugin/json/discuz_post_xss.json"],
		_escData["/plugin/json/discuz_shop_sqli.json"],
		_escData["/plugin/json/discuz_viewthread_xss.json"],
		_escData["/plugin/json/django_urljump.json"],
		_escData["/plugin/json/docker_api.json"],
		_escData["/plugin/json/drupal_geddon2_rce.json"],
		_escData["/plugin/json/elasticsearch_unauth.json"],
		_escData["/plugin/json/glassfish_lfr.json"],
		_escData["/plugin/json/hadoop_yarn_resourcemanager_unauth_rce.json"],
		_escData["/plugin/json/joomla_3.7_sqli.json"],
		_escData["/plugin/json/joomla_contushdvideoshare_lfi.json"],
		_escData["/plugin/json/joomla_departments_sqli.json"],
		_escData["/plugin/json/phpmyadmin_deserialization.json"],
		_escData["/plugin/json/thinkphp5_invokefunction_rce.json"],
		_escData["/plugin/json/thinkphp_5023_rce.json"],
		_escData["/plugin/json/weblogic_debug.json"],
		_escData["/plugin/json/weblogic_ssrf.json"],
		_escData["/plugin/json/wordpress_cmdownloads_rce.json"],
		_escData["/plugin/json/wordpress_dzs_videogallery_xss.json"],
		_escData["/plugin/json/wordpress_jquery_domxss.json"],
		_escData["/plugin/json/wordpress_mainwp_login.json"],
		_escData["/plugin/json/wordpress_sexy_xss.json"],
		_escData["/plugin/json/wordpress_swfupload_xss.json"],
		_escData["/plugin/json/wordpress_wpml_xss.json"],
	},
}
